-- MySQL Script generated by MySQL Workbench
-- Fri Jan  9 09:01:50 2015
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema Synvent
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Synvent
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Synvent` DEFAULT CHARACTER SET latin1 COLLATE latin1_spanish_ci ;
USE `Synvent` ;

-- -----------------------------------------------------
-- Table `Synvent`.`CAT_CATEGORIA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Synvent`.`CAT_CATEGORIA` (
  `id_categoria` INT NOT NULL,
  `desc_categoria` VARCHAR(45) NOT NULL,
  `valido` TINYINT(1) NULL DEFAULT NULL,
  `fecha_creacion` DATETIME NOT NULL,
  `creado_by` VARCHAR(20) NOT NULL,
  `fecha_ult_modific` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id_categoria`),
  UNIQUE INDEX `id_categoria_UNIQUE` (`id_categoria` ASC))
AUTO_INCREMENT = 1;


-- -----------------------------------------------------
-- Table `Synvent`.`CAT_ENT_FEDERATIVA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Synvent`.`CAT_ENT_FEDERATIVA` (
  `id_ent_federativa` INT NOT NULL,
  `desc_corta` VARCHAR(20) NOT NULL,
  `descripcion` VARCHAR(45) NULL DEFAULT NULL,
  `valido` TINYINT(1) NULL DEFAULT NULL,
  `fecha_creacion` DATETIME NOT NULL,
  `creado_by` VARCHAR(20) NOT NULL,
  `fecha_ult_modific` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id_ent_federativa`),
  UNIQUE INDEX `id_ent_federativa_UNIQUE` (`id_ent_federativa` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Synvent`.`CAT_TIPO_PERSONA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Synvent`.`CAT_TIPO_PERSONA` (
  `id_tipo_persona` INT NOT NULL,
  `desc_corta` VARCHAR(20) NOT NULL,
  `descripcion` VARCHAR(45) NULL DEFAULT NULL,
  `valido` TINYINT(1) NULL DEFAULT NULL,
  `fecha_creacion` DATETIME NOT NULL,
  `creado_by` VARCHAR(20) NOT NULL,
  `fecha_ult_modific` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id_tipo_persona`),
  UNIQUE INDEX `id_tipo_persona_UNIQUE` (`id_tipo_persona` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Synvent`.`CAT_MEDIDA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Synvent`.`CAT_MEDIDA` (
  `id_medida` INT NOT NULL,
  `desc_corta` VARCHAR(20) NULL DEFAULT NULL,
  `descripcion` VARCHAR(45) NOT NULL,
  `valido` TINYINT(1) NULL DEFAULT NULL,
  `fecha_creacion` DATETIME NOT NULL,
  `creado_by` VARCHAR(20) NOT NULL,
  `fecha_ult_modific` DATETIME NOT NULL,
  PRIMARY KEY (`id_medida`),
  UNIQUE INDEX `id_medida_UNIQUE` (`id_medida` ASC))
AUTO_INCREMENT = 1;


-- -----------------------------------------------------
-- Table `Synvent`.`CAT_MARCA_MERCANCIA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Synvent`.`CAT_MARCA_MERCANCIA` (
  `id_marca_merca` INT NOT NULL,
  `desc_corta` VARCHAR(20) NOT NULL,
  `descripcion` VARCHAR(45) NOT NULL,
  `valido` TINYINT(1) NULL DEFAULT NULL,
  `fecha_creacion` DATETIME NOT NULL,
  `creado_by` VARCHAR(20) NOT NULL,
  `fecha_ult_modific` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id_marca_merca`),
  UNIQUE INDEX `id_marca_merca_UNIQUE` (`id_marca_merca` ASC))
AUTO_INCREMENT = 1;


-- -----------------------------------------------------
-- Table `Synvent`.`CAT_TIPO_VENTA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Synvent`.`CAT_TIPO_VENTA` (
  `id_tipo_venta` INT NOT NULL,
  `desc_corta` VARCHAR(20) NOT NULL,
  `descripcion` VARCHAR(45) NOT NULL,
  `valido` TINYINT(1) NULL DEFAULT NULL,
  `fecha_creacion` DATETIME NOT NULL,
  `creado_by` VARCHAR(20) NOT NULL,
  `fecha_ult_modific` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id_tipo_venta`),
  UNIQUE INDEX `id_tipo_venta_UNIQUE` (`id_tipo_venta` ASC))
AUTO_INCREMENT = 1;


-- -----------------------------------------------------
-- Table `Synvent`.`DIRECCION`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Synvent`.`DIRECCION` (
  `id_direccion` INT NOT NULL,
  `calle` VARCHAR(45) NULL DEFAULT NULL,
  `num_interior` VARCHAR(10) NOT NULL,
  `num_exterior` VARCHAR(10) NOT NULL,
  `colonia_poblacion` VARCHAR(45) NOT NULL,
  `municipio_deleg` VARCHAR(45) NOT NULL,
  `id_entidad_fed` INT NOT NULL,
  `cp` VARCHAR(45) NULL DEFAULT NULL,
  `fecha_creacion` DATETIME NOT NULL,
  `creado_by` VARCHAR(20) NOT NULL,
  `fecha_ult_modific` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id_direccion`),
  UNIQUE INDEX `id_direccion_UNIQUE` (`id_direccion` ASC),
  INDEX `id_entidad_fed` (`id_entidad_fed` ASC),
  CONSTRAINT `id_entidad_fed`
    FOREIGN KEY (`id_entidad_fed`)
    REFERENCES `Synvent`.`CAT_ENT_FEDERATIVA` (`id_ent_federativa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
AUTO_INCREMENT = 1;


-- -----------------------------------------------------
-- Table `Synvent`.`PERSONA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Synvent`.`PERSONA` (
  `id_persona` INT NOT NULL,
  `nombre` VARCHAR(20) NOT NULL,
  `apellido_pat` VARCHAR(45) NOT NULL,
  `apellido_mat` VARCHAR(45) NULL DEFAULT NULL,
  `comentarios` VARCHAR(30) NULL DEFAULT NULL,
  `id_direccion` INT NULL DEFAULT NULL,
  `id_tipo_persona` INT NULL DEFAULT NULL,
  `rfc` VARCHAR(30) NULL DEFAULT NULL,
  `email` VARCHAR(40) NULL DEFAULT NULL,
  `fecha_creacion` DATETIME NOT NULL,
  `creado_by` VARCHAR(20) NOT NULL,
  `fecha_ult_modific` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id_persona`),
  UNIQUE INDEX `id_persona_UNIQUE` (`id_persona` ASC),
  INDEX `id_direccion_idx` (`id_direccion` ASC),
  INDEX `id_tipo_persona` (`id_tipo_persona` ASC),
  CONSTRAINT `id_direccion`
    FOREIGN KEY (`id_direccion`)
    REFERENCES `Synvent`.`DIRECCION` (`id_direccion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_tipo_persona`
    FOREIGN KEY (`id_tipo_persona`)
    REFERENCES `Synvent`.`CAT_TIPO_PERSONA` (`id_tipo_persona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Synvent`.`SUCURSAL`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Synvent`.`SUCURSAL` (
  `id_sucursal` INT NOT NULL,
  `descripcion` VARCHAR(45) NULL DEFAULT NULL,
  `id_direccion` VARCHAR(45) NULL DEFAULT NULL,
  `responsable` INT NULL DEFAULT NULL,
  `fecha_creacion` DATETIME NOT NULL,
  `creado_by` VARCHAR(20) NOT NULL,
  `fecha_ult_modific` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id_sucursal`),
  UNIQUE INDEX `id_sucursal_UNIQUE` (`id_sucursal` ASC),
  INDEX `responsable_idx` (`responsable` ASC),
  CONSTRAINT `responsable`
    FOREIGN KEY (`responsable`)
    REFERENCES `Synvent`.`PERSONA` (`id_persona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Synvent`.`PRODUCTO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Synvent`.`PRODUCTO` (
  `id_producto` INT NOT NULL,
  `codigo_barra` VARCHAR(14) NULL DEFAULT NULL,
  `cve_producto` VARCHAR(25) NULL DEFAULT NULL,
  `descripcion_prod` VARCHAR(90) NULL DEFAULT NULL,
  `cantidad_prod` FLOAT NULL DEFAULT NULL,
  `modelo_vehiculo` INT NULL DEFAULT NULL,
  `id_marca_producto` INT NULL DEFAULT NULL,
  `id_medida` INT NULL DEFAULT NULL,
  `id_categoria` INT NULL DEFAULT NULL,
  `valido` TINYINT(1) NULL DEFAULT NULL,
  `stock` INT NULL DEFAULT NULL,
  `fecha_creacion` DATETIME NOT NULL,
  `creado_by` VARCHAR(20) NOT NULL,
  `fecha_ult_modific` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id_producto`),
  INDEX `categoria_idx` (`id_categoria` ASC),
  INDEX `medida_idx` (`id_medida` ASC),
  INDEX `marcaProducto_idx` (`id_marca_producto` ASC),
  UNIQUE INDEX `id_producto_UNIQUE` (`id_producto` ASC),
  CONSTRAINT `id_categoria`
    FOREIGN KEY (`id_categoria`)
    REFERENCES `Synvent`.`CAT_CATEGORIA` (`id_categoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_medida`
    FOREIGN KEY (`id_medida`)
    REFERENCES `Synvent`.`CAT_MEDIDA` (`id_medida`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_marca_producto`
    FOREIGN KEY (`id_marca_producto`)
    REFERENCES `Synvent`.`CAT_MARCA_MERCANCIA` (`id_marca_merca`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'CREATE TABLE [Medida] (\n	[cvemedida] [varchar] (25) NOT NULL /* comment truncated */ /* ,\n	[medida] [varchar] (25) NOT NULL \n) ON [PRIMARY]*/';


-- -----------------------------------------------------
-- Table `Synvent`.`PRECIO_PRODUCTO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Synvent`.`PRECIO_PRODUCTO` (
  `id_precio` INT NOT NULL,
  `id_producto` INT NOT NULL,
  `costo` DOUBLE NOT NULL,
  `precio` DOUBLE NOT NULL,
  `valido` TINYINT(1) NULL DEFAULT NULL,
  `fecha_creacion` DATETIME NOT NULL,
  `creado_by` VARCHAR(20) NOT NULL,
  `fecha_ult_modific` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id_precio`, `id_producto`),
  INDEX `id_producto` (`id_producto` ASC),
  CONSTRAINT `id_producto`
    FOREIGN KEY (`id_producto`)
    REFERENCES `Synvent`.`PRODUCTO` (`id_producto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
AUTO_INCREMENT = 1;


-- -----------------------------------------------------
-- Table `Synvent`.`USUARIO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Synvent`.`USUARIO` (
  `id_usuario` INT NOT NULL,
  `usuario` VARCHAR(45) NOT NULL,
  `id_persona` INT NOT NULL,
  `contrasena` VARCHAR(20) NOT NULL,
  `valido` TINYINT(1) NULL DEFAULT NULL,
  PRIMARY KEY (`id_usuario`),
  UNIQUE INDEX `id_usuario_UNIQUE` (`id_usuario` ASC),
  INDEX `usuario_idx` (`usuario` ASC),
  INDEX `id_persona` (`id_persona` ASC),
  CONSTRAINT `id_persona`
    FOREIGN KEY (`id_persona`)
    REFERENCES `Synvent`.`PERSONA` (`id_persona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Synvent`.`VENTA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Synvent`.`VENTA` (
  `id_venta` INT NOT NULL,
  `numero_venta` VARCHAR(45) NULL DEFAULT NULL,
  `id_tipo_venta` INT NOT NULL,
  `porcentaje_descuento` FLOAT NULL DEFAULT NULL,
  `piezas` DOUBLE NOT NULL,
  `subtotal` DOUBLE NULL DEFAULT NULL,
  `total` DOUBLE NULL DEFAULT NULL,
  `fecha_venta` DATETIME NOT NULL,
  `realizo_factura` TINYINT(1) NULL DEFAULT NULL,
  `id_usuario` INT NULL DEFAULT NULL,
  `id_cliente` INT NULL DEFAULT NULL,
  `fecha_creacion` DATETIME NOT NULL,
  `creado_by` VARCHAR(20) NOT NULL,
  `fecha_ult_modific` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id_venta`),
  INDEX `tipoVenta_idx` (`id_tipo_venta` ASC),
  INDEX `numero_venta_idx` (`numero_venta` ASC),
  INDEX `id_usuario` (`id_usuario` ASC),
  INDEX `id_cliente` (`id_cliente` ASC),
  CONSTRAINT `id_tipo_venta`
    FOREIGN KEY (`id_tipo_venta`)
    REFERENCES `Synvent`.`CAT_TIPO_VENTA` (`id_tipo_venta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_usuario`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `Synvent`.`USUARIO` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_cliente`
    FOREIGN KEY (`id_cliente`)
    REFERENCES `Synvent`.`PERSONA` (`id_persona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
AUTO_INCREMENT = 1;


-- -----------------------------------------------------
-- Table `Synvent`.`COMPRA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Synvent`.`COMPRA` (
  `id_compra` INT NOT NULL,
  `num_factura` VARCHAR(45) NULL DEFAULT NULL,
  `proveedor` VARCHAR(45) NOT NULL,
  `mes_registro` VARCHAR(45) NOT NULL,
  `total` VARCHAR(45) NOT NULL,
  `subtotal` VARCHAR(45) NOT NULL,
  `fecha` VARCHAR(45) NOT NULL,
  `cve_factura` VARCHAR(45) NULL DEFAULT NULL,
  `fecha_creacion` DATETIME NOT NULL,
  `creado_by` VARCHAR(20) NOT NULL,
  `fecha_ult_modific` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id_compra`),
  UNIQUE INDEX `id_compra_UNIQUE` (`id_compra` ASC))
AUTO_INCREMENT = 1;


-- -----------------------------------------------------
-- Table `Synvent`.`PRODUCTO_VENTA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Synvent`.`PRODUCTO_VENTA` (
  `id_producto_venta` INT NOT NULL,
  `id_producto` INT NOT NULL,
  `id_venta` INT NOT NULL,
  `costo` DOUBLE NOT NULL,
  `precio_venta` DOUBLE NOT NULL,
  `fecha_venta` DATETIME NOT NULL,
  `fecha_creacion` DATETIME NOT NULL,
  `creado_by` VARCHAR(20) NOT NULL,
  `fecha_ult_modific` DATETIME NOT NULL,
  PRIMARY KEY (`id_producto_venta`),
  INDEX `id_producto_idx` (`id_producto` ASC, `id_venta` ASC),
  INDEX `id_venta_idx` (`id_venta` ASC),
  CONSTRAINT `id_producto`
    FOREIGN KEY (`id_producto` , `id_venta`)
    REFERENCES `Synvent`.`PRODUCTO` (`id_producto` , `id_producto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_venta`
    FOREIGN KEY (`id_venta`)
    REFERENCES `Synvent`.`VENTA` (`id_venta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
